version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Install SSH Client"
          command: |
              sudo apt-get update && sudo apt-get install -y openssh-client
      - add_ssh_keys:
          fingerprints:
            - "{{ .Environment.SSH }}"
      - run:
          name: "SSH into Remote Server"
          command: |
              eval $(ssh-agent -s)
              ssh-add ~/.ssh/id_rsa
              ssh -o StrictHostKeyChecking=no {$USERNAME}@$HOST 'bash -s' < /home/ubuntu/devops/laraveldeploy.sh
      - run:
          name: "Cleanup SSH Agent"
          command: |
              ssh-agent -k


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master