version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Laravel"
          command: |
                echo "SSH into the host"
                ssh -o StrictHostKeyChecking=no -i $SSH $USERNAME@$HOST -t 'echo $SSH_KEY >> ~/.ssh/authorized_keys'
                echo "Executing shell script"
                sh /home/ubuntu/devops/laraveldeploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master