version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.1-node-browsers
    steps:
      - checkout
      - run:
          name: "Laravel"
          command: |
            echo "Laravel App"
            {SSH} {USERNAME}@{HOSTNAME} "cd /home/ubuntu/devops && ./laraveldeploy.sh"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master