version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    environment:
      SSH: ${{ secrets.SSH_KEY }}
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
    steps:
      - checkout
      - run:
          name: "Install SSH Client"
          command: |
              sudo apt-get update && sudo apt-get install -y openssh-client
  


      - run:
          name: "SSH into Remote Server"
          command: |
              ssh -o StrictHostKeyChecking=no ubuntu@$HOST -t '/home/ubuntu/devops/deploy.sh'
      - run:
          name: "Cleanup SSH Agent"
          command: |
              ssh-agent -k

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master