version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ubuntu-1804:latest
    steps:
      - checkout
      - run:
          name: "Laravel"
          command: |
            echo "Laravel App"
            echo "Preparing to deploy to production server"
            apk add openssh-client
            'which ssh-agent || (apk add --update openssh)'
            eval $(ssh-agent -s)
            echo "$SSH" | tr -d '\r' | ssh-add - > /dev/null
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            ssh-keyscan $HOST >> ~/.ssh/known_hosts

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master