version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        environment:
            SSH: $SSH
            USERNAME : $USERNAME
            HOST: $HOST
    steps:
      - checkout
      - run:
          name: "Install SSH Client"
          command: |
              sudo apt-get update && sudo apt-get install -y openssh-client
      - add_ssh_keys:
          fingerprints:
            - "{ SSH }"
      - run:
          name: "SSH into Remote Server"
          command: |
              eval $(ssh-agent -s)
              echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
              mkdir -p ~/.ssh
              chmod 700 ~/.ssh
              touch ~/.ssh/known_hosts
              chmod 644 ~/.ssh/known_hosts
              ssh-keyscan $HOST >> ~/.ssh/known_hosts
              ssh -o StrictHostKeyChecking=no ubuntu@$HOST -t '/home/ubuntu/devops/deploy.sh'
      - run:
          name: "Cleanup SSH Agent"
          command: |
              ssh-agent -k


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master