version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Deploy laravel App"
          command: |
              ssh -o StrictHostKeyChecking=no $USERNAME@$HOST -t 'sh /home/ubuntu/devops/laraveldeploy.sh'
        

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master