version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    environment:
      SSH: ${{ secrets.SSH_KEY }}
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
    steps:
      - checkout
      - run:
          name: "SSH into Remote Server"
          command: |
              ssh -o StrictHostKeyChecking=no ubuntu@54.179.150.73 -t 'sh /home/ubuntu/devops/laraveldeploy.sh'
        

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master