version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Login with SSH"
          command: |
            ssh $USERNAME@$HOST
            echo "$KNOWN_HOST_KEY" >> ~/.ssh/known_hosts
      - run:
          name: "Laravel"
          command: |
              /home/ubuntu/devops/laraveldeploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master