version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    environment:
      HOSTNAME: $HOST
      USERNAME: $USERNAME
    steps:
      - checkout
      - run:
          name: "SSH into Remote Server"
          command: |
              ssh -o StrictHostKeyChecking=no $USERNAME@$HOSTNAME -t 'sh /home/ubuntu/devops/laraveldeploy.sh'
        

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master