version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Laravel"
          command: |
                echo "SSH into the host"
                ssh -o StrictHostKeyChecking=no -i $SSH $USERNAME@$HOST -t '/home/ubuntu/devops/laraveldeploy.sh'

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master